pipeline {
  agent { label 'agent193' }

  stages {
    stage('Test K8s Access') {
  steps {
    withKubeConfig([credentialsId: 'jenkins-kubeconfig']) {
      sh 'kubectl get nodes'
        }
      }
    }
  }
}
