pipeline {
    agent { label 'agent193' }
     stages {
        stage('Deploy to K8s') {
            steps {
                withKubeConfig([credentialsId: 'certificate_file', serverUrl: 'https://10.0.0.193:6443']) {
                    sh 'kubectl get pods'
                    // Add your kubectl commands here
                }
            }
        }
    }
}