---
- name: Create Deployment and Service
  hosts: localhost
  tasks:
    - name: Create deployment
      k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: abctechnologies-deployment
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: abctechnologies
            template:
              metadata:
                labels:
                  app: abctechnologies
              spec:
                containers:
                  - name: abctechnologies-container
                    image: docker.io/demsdocker/abctechnologies
                    ports:
                      - containerPort: 8180
    - name: Create service
      k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: abctechnologies-service
          spec:
            selector:
              app: abctechnologies
            ports:
              - protocol: TCP
                port: 80
                targetPort: 8180
            type: LoadBalancer
