apiVersion: apps/v1
kind: Deployment
metadata:
    name: abctechnologies-dep
    namespace: abc-tech
spec:
    replicas: 2
    minReadySeconds: 45
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 2
    selector:
        matchLabels:
            app: abc-tech-app
    template:
        metadata:
            labels:
                app: abc-tech-app
        spec:
            tolerations:
                - key: "node-role.kubernetes.io/control-plane"
                  operator: "Exists"
            containers:
                - name: app
                  image: demsdocker/abctechnologies
                  ports:
                      - containerPort: 8080
                        name: http
                  livenessProbe:
                    httpGet:
                      path: /abctechnologies-1.0
                      port: 8080
                    initialDelaySeconds: 60
                    periodSeconds: 20
                  readinessProbe:
                    httpGet:
                      path: /abctechnologies-1.0
                      port: 8080
                    initialDelaySeconds: 30
                    periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
    name: abc-tech-service
    namespace: abc-tech
spec:
    type: NodePort
    selector:
        app: abc-tech-app
    ports:
        - name: http
          port: 8080
          targetPort: 8080
          nodePort: 30080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abc-tech-ingress
  namespace: abc-tech
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /abctechnologies-1.0/$1
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: abc-tech-service
            port:
              number: 8080
