---
- name: Build and Push Docker Image
  hosts: localhost
  tasks:
    - name: Build Docker image
      docker_image:
        name: abctechnologies
        source: build # Explicitly set the source option to "build"
        path: /var/jenkins-agent/workspace/ABC_AnsibleK8s
        push: true
      register: abctechnologies

    - name: Debug Docker image build result
      debug:
        var: abctechnologies
