# apiVersion: apps/v1
# kind: Deployment
# metadata:
#     name: abctechnologies-dep
# spec:
#     replicas: 2
#     minReadySeconds: 45
#     strategy:
#         type: RollingUpdate
#         rollingUpdate:
#             maxUnavailable: 1
#             maxSurge: 2
#     selector:
#         matchLabels:
#             app: abc-tech-app
#     template:
#         metadata:
#             labels:
#                 app: abc-tech-app
#         spec:
#             tolerations: # Add tolerations here
#                 - key: "node-role.kubernetes.io/control-plane"
#                   operator: "Exists"
#             containers:
#                 - name: app
#                   image: demsdocker/abctechnologies
#                   ports:
#                       - containerPort: 8080

# Add these to your deployment YAML

apiVersion: apps/v1
kind: Deployment
metadata:
    name: abctechnologies-dep

spec:
  template:
    spec:
      containers:
      - name: your-container
        readinessProbe:
          httpGet:
            path: demsdocker/abctechnologiesnt
            port: 8080-port
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
    name: abc-tech-service
spec:
    type: NodePort
    selector:
        app: abc-tech-app
    ports:
        - port: 80
          targetPort: 8080
