apiVersion: v1
kind: Service
metadata:
  name: abc-tech-service
  namespace: abc-tech
spec:
  type: LoadBalancer
  selector:
    app: abc-tech-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
