- hosts: localhost
  become: yes
  tasks:
    - name: start a container
      community.docker.docker_container:
        name: abc-application
        image: demsdocker/abctechnologies
        state: started
        ports:
          - "1234:8080"
      register: out

    - debug:
        var: out