- hosts: localhost
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.10
  connection: local
  tasks:
    - name: Start a Docker container
      community.docker.docker_container:
        name: abc-application
        image: demsdocker/abctechnologies
        state: started
        ports:
          - "1234:8080"
      register: container_output

    - name: Show container output
      debug:
        var: container_output
