- hosts: localhost
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.10
  connection: local

  tasks:
    - name: Start a container
      community.docker.docker_container:
        name: abc-application
        image: demsdocker/abctechnologies
        state: started
        ports:
          - "1234:8080"
      register: out

    - name: Show container start output
      debug:
        var: out
